plugins {
    id 'java'
    id 'jacoco'
    id 'maven-publish'
    id 'com.enonic.defaults' version '2.1.7'
    id 'com.enonic.xp.base'
}

dependencies {
    compileOnly xplibs.api.script
    compileOnly xplibs.api.portal

    implementation ( libs.saxon.he ) {
        exclude group: 'xml-apis'
    }

    testImplementation( platform( libs.junit.bom ) )
    testImplementation( platform( libs.mockito.bom ) )
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher
    testImplementation libs.mockito.junit.jupiter
    testImplementation "com.enonic.xp:testing:${xpVersion}"
    testRuntimeOnly libs.graalvm.js
}

jacocoTestReport {
    reports {
        xml.required = true
        html.required = true
    }
}

check.dependsOn jacocoTestReport

test {
    useJUnitPlatform()
}

def testGraalJs = tasks.register('testGraalJs', Test) {
    group = 'verification'
    description = 'Runs tests with the GraalJS script engine.'
    useJUnitPlatform()
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
    systemProperty 'xp.script-engine', 'GraalJS'
    shouldRunAfter test
}

check.dependsOn testGraalJs

artifacts {
    archives jar
}

repositories {
    mavenCentral()
    xp.enonicRepo('dev')
}
